### ISSUE TITLE
生成纹理需要的显存太高，24G不够，有量化模型吗

### ISSUE THREAD

**Issue by harveyff** [Tencent-Hunyuan/Hunyuan3D-2.1#80]
现在24G显存的机器生成不了纹理，一运行就显存爆了。官方有计划出量化模型吗？
或者哪位有知道如何在24G显存跑纹理吗，感激不尽

**Comment by MatrixHan** [comment]
我16GB  也是不够，报错是这个。
CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by WenfuBi** [comment]
我也是24G不够，在生成MESH的时候大概是占用8G显存，但是生成Texture的时候，显存占用飙升至24G+，然后直接报错

**Comment by a2939619811-ai** [comment]
> 我也是24G不够，在生成MESH的时候大概是占用8G显存，但是生成Texture的时候，显存占用飙升至24G+，然后直接报错

请问你后面解决了吗

**Comment by WenfuBi** [comment]
> > 我也是24G不够，在生成MESH的时候大概是占用8G显存，但是生成Texture的时候，显存占用飙升至24G+，然后直接报错
> 
> 请问你后面解决了吗

解决了，换了个服务器😂，A6000，48G显存
